{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galaxy-ng-pvc
  namespace: galaxy-ng
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass | default "" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end}}
